// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5t1alIEo1vQMui3buJEo6qxh1Pjv5sPc',
    appId: '1:450533182221:web:fb021503bafa8f34c43e44',
    messagingSenderId: '450533182221',
    projectId: 'accounting-service-c1433',
    authDomain: 'accounting-service-c1433.firebaseapp.com',
    storageBucket: 'accounting-service-c1433.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_ofWYIifeIFyxwIvVTqKO53Ljw2EUNY',
    appId: '1:450533182221:android:45013d720b26bd29c43e44',
    messagingSenderId: '450533182221',
    projectId: 'accounting-service-c1433',
    storageBucket: 'accounting-service-c1433.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9wh-1FbR0l6XpAF8izKpQPrqf8cqNWE',
    appId: '1:450533182221:ios:1a44034323821e14c43e44',
    messagingSenderId: '450533182221',
    projectId: 'accounting-service-c1433',
    storageBucket: 'accounting-service-c1433.appspot.com',
    iosClientId: '450533182221-58lbsdpkpvk26h11lagvekjvdshhuljn.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountingService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc9wh-1FbR0l6XpAF8izKpQPrqf8cqNWE',
    appId: '1:450533182221:ios:29b9c343dfae23c8c43e44',
    messagingSenderId: '450533182221',
    projectId: 'accounting-service-c1433',
    storageBucket: 'accounting-service-c1433.appspot.com',
    iosClientId: '450533182221-k8e2sep4eh6g2p7avd3l79947gku1pjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountingService.RunnerTests',
  );
}
